spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8001
  ssl:
    key-store: classpath:keystore.p12
    key-alias: tomcat
    enabled: true
    key-store-password: 456789
    key-store-type: PKCS12
dubbo:
  application:
    name: dubbo-provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 1000